### PR TITLE
Database creation

### PR DESCRIPTION
**Pull request by jimk-bdrc**
Implements #1
Mysql implementation of image db.

### CODE REVIEW

**Review by eroux — APPROVED** [review]
Looks good, thanks!

**Comment by jimk-bdrc** [comment]
Some review comments:
1. Storage schema
There are hooks in the `content` schema which depend on the`storage` schema. 
The storage schema depends on an OCFL implementation.
How do we get to the OCFL implementation?

2. OCFL capacity
The `storage` schema seems to have a dependency on each file being a discrete object. This is guaranteed to be slow and large at the scale we operate on. It is completely possible for an object to represent a folder, each of which has an inventory (which represents the files, along with their checksums).

```
object-root/
├── 0=ocfl_object_1.0
├── inventory.json
└── content/
    ├── file1.txt
    └── file2.txt
```
has an inventory.json
```
{
  "id": "object-1",
  "type": "https://ocfl.io/1.0/spec/#inventory",
  "digestAlgorithm": "sha512",
  "head": "v1",
  "contentDirectory": "content",
  "manifest": {
    "sha512-digest-of-file1": ["content/file1.txt"],
    "sha512-digest-of-file2": ["content/file2.txt"]
  },
  "versions": {
    "v1": {
      "state": {
        "sha512-digest-of-file1": ["content/file1.txt"],
        "sha512-digest-of-file2": ["content/file2.txt"]
      }
    }
  }
}
```

3. Sha digest of file. I included in the  `storage.file` table a text repr of the  the  algorithm that generated the `digest` This might not be needed because the file's `storage.object` should hold that string, just as the container does in `inventory.json`. Might not be a bad idea to model the storage schema around the OCFL content model (it's pretty close.)

**Comment by eroux** [comment]
1. The idea is to start with this db and use it to create ocfl later, there's no dependency on an existing ocfl implementation, it's just a db

2. That's not my interpretation, why would  each object need to be a file?

3. Let's settle on  a hash algorith and stick with it instead of having these different possibilities. Sha256 is supported by both ocfl and s3, I propose we use it

**Comment by jimk-bdrc** [comment]
And just for thrills, because this is easiest now, I'm going to revert all the key types to UNSIGNED integer, so that keys can have values up to 4Billion. With 100 million known files, even the limit of 2Bn for signed integers feels tight. Costs nothing, allows room

**Comment by eroux** [comment]
> I'm finding that the checksum is not natively supported on s3. Even the etag is not necessarily the MD5 of the file (e.g. when the object is > 16MB). Looking in [a3api get-objects-api](https://docs.aws.amazon.com/cli/latest/reference/s3api/get-object-attributes.html) These checksums are only available when they are created with the object, and we have no workflow that does that now.

see https://aws.amazon.com/fr/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/ , unless they rolled it back

> Restricting your choices at the beginning will cause pain at some point - since change is a given. As well, this restriction creates a hardwired hidden (implicit) dependency between the database and all of the software tools in the implementation: the database writers and the database readers. As software development proceeds, this will make it more difficult and slower. At the very least, we should be including some kind of algorithm descriptor, even if the only allowed value is sha256.

what I propose is to have a column `digest_sha256` so that the algorithm is made explicit. When we want to change I think the best strategy will be to add a new column `digest_whatever` with the values of the new hash, instead of having just one possible digest value. Having one column with a defined algorithm will make things better, that way when we transition to the column `digest_whatever` we can have a transition period with the two digests in the database, we won't need to migrate everything at once. In the transition period some software can use the old column, some the new one. I think it's easier this way

**Pull request merged**
